# -*- coding: utf-8 -*-
"""code_workflow2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-UNe5Cf2Ol7Ti-OF8pKlrSM-7Jn90g5E

# **Model Training**
"""

pip install catboost

import pandas as pd
import numpy as np
from catboost import CatBoostClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_curve, auc, confusion_matrix
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

X = dataset.drop(columns='Cover_Type').values
y = dataset['Cover_Type'].values - 1

scaler = StandardScaler()
X = scaler.fit_transform(X)

kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

accuracy_per_fold = []
precision_per_fold = []
recall_per_fold = []
f1_per_fold = []
roc_auc_per_fold = []
confusion_matrices = []

for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
    print(f"Training fold {fold + 1}")

    # Split data
    X_train, X_val = X[train_idx], X[val_idx]
    y_train, y_val = y[train_idx], y[val_idx]

    # Initialize CatBoostClassifier
    model = CatBoostClassifier(
        iterations=500,          # Number of boosting iterations
        learning_rate=0.1,       # Learning rate
        depth=6,                 # Depth of the trees
        loss_function='MultiClass',
        verbose=False            # Disable verbose output for each iteration
    )

    # Train the model
    model.fit(X_train, y_train, eval_set=(X_val, y_val), early_stopping_rounds=20)

    # Predict on validation data
    y_pred_val = model.predict(X_val)

    # Calculate metrics
    accuracy = accuracy_score(y_val, y_pred_val)
    precision = precision_score(y_val, y_pred_val, average='weighted')
    recall = recall_score(y_val, y_pred_val, average='weighted')
    f1 = f1_score(y_val, y_pred_val, average='weighted')

    accuracy_per_fold.append(accuracy)
    precision_per_fold.append(precision)
    recall_per_fold.append(recall)
    f1_per_fold.append(f1)

    # Confusion Matrix
    cm = confusion_matrix(y_val, y_pred_val)
    confusion_matrices.append(cm)

    # ROC and AUC
    fpr = {}
    tpr = {}
    roc_auc = {}
    y_pred_prob = model.predict_proba(X_val)  # Get prediction probabilities for ROC
    for i in range(7):  # 7 classes
        fpr[i], tpr[i], _ = roc_curve(y_val, y_pred_prob[:, i], pos_label=i)
        roc_auc[i] = auc(fpr[i], tpr[i])

    roc_auc_per_fold.append(roc_auc)

    # Plot ROC curve for this fold
    plt.figure()
    for i in range(7):
        plt.plot(fpr[i], tpr[i], label=f'Class {i} (area = {roc_auc[i]:.2f})')
    plt.plot([0, 1], [0, 1], 'k--')
    plt.title(f'ROC Curve - Fold {fold + 1}')
    plt.legend()
    plt.show()

mean_fpr = np.linspace(0, 1, 100)
mean_tpr = {i: np.zeros_like(mean_fpr) for i in range(7)}  # 7 classes
mean_roc_auc = {}

# After collecting ROC curves for each fold
for fold, roc_auc in enumerate(roc_auc_per_fold):
    for i in range(7):
        fpr, tpr, _ = roc_curve(y_val, y_pred_prob[:, i], pos_label=i)  # Recompute for each class
        mean_tpr[i] += np.interp(mean_fpr, fpr, tpr)  # Interpolate TPR at standard FPR points
        mean_tpr[i][0] = 0.0  # Ensure the curve starts at (0, 0)

# Finalize average TPR and ROC AUC for each class
for i in range(7):
    mean_tpr[i] /= len(roc_auc_per_fold)
    mean_tpr[i][-1] = 1.0  # Ensure the curve ends at (1, 1)
    mean_roc_auc[i] = auc(mean_fpr, mean_tpr[i])

# Plot the average ROC curve for each class
plt.figure()
for i in range(7):
    plt.plot(mean_fpr, mean_tpr[i], label=f'Class {i} (area = {mean_roc_auc[i]:.2f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line (random classifier)
plt.title('Average ROC Curve Across All Folds')
plt.legend(loc='lower right')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.show()

average_cm = np.mean(confusion_matrices, axis=0)
plt.figure(figsize=(10, 7))
sns.heatmap(average_cm, annot=True, fmt='.2f', cmap='Blues')
plt.title('Average Confusion Matrix Across Folds')
plt.show()

print(f"Average Accuracy: {np.mean(accuracy_per_fold)}")
print(f"Average Precision: {np.mean(precision_per_fold)}")
print(f"Average Recall: {np.mean(recall_per_fold)}")
print(f"Average F1-score: {np.mean(f1_per_fold)}")